# Generated by Django 3.0.6 on 2020-07-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '文章'), (2, '照片'), (3, '视频'), (4, '音频'), (5, '商品')], verbose_name='类型')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '文章'), (2, '照片'), (3, '视频'), (4, '音频'), (5, '商品')], verbose_name='类型')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('recommend', models.BooleanField(default=False, help_text='如果作为推荐，则加入推荐系统', verbose_name='是否推荐')),
                ('preview', models.ForeignKey(help_text='图/音视频', on_delete=django.db.models.deletion.CASCADE, to='post.Material', verbose_name='预览')),
            ],
            options={
                'verbose_name': '摘要',
                'verbose_name_plural': '摘要',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('visit', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('previews', models.ManyToManyField(to='post.Material', verbose_name='商品预览')),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
    ]
