# Generated by Django 3.1.8 on 2021-05-03 03:55

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='正文'),
        ),
    ]
