# Generated by Django 3.0.6 on 2020-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_time'], 'verbose_name': '摘要', 'verbose_name_plural': '摘要'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='previews',
        ),
        migrations.AddField(
            model_name='goods',
            name='previews',
            field=models.CharField(default='', max_length=640, verbose_name='商品预览'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '可见'), (2, '不可见')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '可见'), (2, '不可见')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='preview',
            field=models.CharField(help_text='图/音视频', max_length=200, verbose_name='预览'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
