# Generated by Django 3.1.8 on 2021-05-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210503_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
