# Generated by Django 3.0.6 on 2020-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200705_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='mainpage',
            field=models.BooleanField(default=False, help_text='是否首页可见，否则只能在后台看到', verbose_name='是否首页可见'),
        ),
    ]
