# Generated by Django 3.2.7 on 2021-11-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='大小')),
                ('hash_val', models.SlugField(max_length=64, unique=True, verbose_name='哈希值')),
                ('hash_type', models.SlugField(default='sha256', max_length=10, verbose_name='哈希类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('link', models.SlugField(max_length=200, verbose_name='链接')),
                ('link_type', models.SmallIntegerField(choices=[(1, '图片'), (2, '视频'), (3, '音频')], verbose_name='链接类型')),
                ('format', models.CharField(max_length=10, verbose_name='格式')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '不可见'), (2, '删除')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='大小')),
                ('hash_val', models.SlugField(max_length=64, unique=True, verbose_name='哈希值')),
                ('hash_type', models.SlugField(default='sha256', max_length=10, verbose_name='哈希类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=64, verbose_name='文件名')),
                ('link', models.SlugField(max_length=200, verbose_name='链接')),
                ('link_type', models.SmallIntegerField(choices=[(1, '文件'), (2, '链接'), (3, '文本')], default=1, verbose_name='链接类型')),
                ('type', models.SlugField(max_length=32, verbose_name='文件类型')),
                ('status', models.SmallIntegerField(choices=[(0, '审核'), (1, '正常'), (2, '隐藏')], default=0, verbose_name='状态')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
    ]
