# Generated by Django 3.1.4 on 2021-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('content', models.CharField(max_length=256, verbose_name='回复内容')),
                ('content_type', models.SmallIntegerField(choices=[(1, '文本'), (2, '图片'), (3, '音频'), (4, '视频')], default=1, verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '消息内容',
                'verbose_name_plural': '消息内容',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文件名')),
                ('size', models.PositiveIntegerField(verbose_name='大小')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('link', models.SlugField(max_length=200, verbose_name='链接')),
                ('link_type', models.SmallIntegerField(choices=[(1, '文件'), (2, '链接'), (3, '文本')], default=1, verbose_name='链接类型')),
                ('hash_val', models.SlugField(max_length=64, unique=True, verbose_name='哈希值')),
                ('hash_type', models.SlugField(default='sha256', max_length=10, verbose_name='哈希类型')),
                ('type', models.SlugField(max_length=32, verbose_name='文件类型')),
                ('status', models.SmallIntegerField(choices=[(0, '审核'), (1, '正常'), (2, '隐藏')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='WxAutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=20, unique=True, verbose_name='规则名称')),
                ('keyword', models.CharField(max_length=20, unique=True, verbose_name='关键词')),
                ('reply_type', models.SmallIntegerField(choices=[(0, '随机回复一条'), (1, '全部回复')], default=1, verbose_name='回复方式')),
                ('contents', models.ManyToManyField(to='resource.Content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '自动回复',
                'verbose_name_plural': '自动回复',
            },
        ),
    ]
