# Generated by Django 3.1.8 on 2021-05-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20210503_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxautoreply',
            name='contents',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='WxAutoReply',
        ),
    ]
