# Generated by Django 3.1.8 on 2021-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_studycollect_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('previews', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=16)),
                ('addr', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商品信息收集',
                'verbose_name_plural': '商品信息收集',
                'ordering': ['-created_time'],
            },
        ),
    ]
