# Generated by Django 3.1.8 on 2021-05-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect', '0003_presentcollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentcollect',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentcollect',
            name='addr',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='presentcollect',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentcollect',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='presentcollect',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
