# Generated by Django 3.1.8 on 2021-05-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('preview', models.CharField(max_length=200, verbose_name='商品预览')),
                ('content', models.TextField(verbose_name='正文')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '可见'), (2, '不可见')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('price', models.FloatField(verbose_name='价格')),
                ('nums', models.PositiveIntegerField(default=1, verbose_name='库存')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('total_fee', models.FloatField(default=0, verbose_name='总费用')),
                ('payed', models.FloatField(default=0, verbose_name='实付款')),
                ('address', models.CharField(default='', max_length=200, verbose_name='收货地址')),
                ('out_trade_no', models.SlugField(default='', max_length=32, verbose_name='微信后台订单号')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待配送'), (2, '配送中'), (3, '已取消'), (4, '已拒收'), (5, '已完成')], default=0, verbose_name='状态')),
                ('refund_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='退款原因')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Appraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(choices=[(1, '非常差'), (2, '差'), (3, '一般'), (4, '好'), (5, '非常好')], default=5, verbose_name='描述相符')),
                ('content', models.CharField(default='', max_length=512, verbose_name='评价内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'ordering': ['-created_time'],
            },
        ),
    ]
