# Generated by Django 3.1.8 on 2021-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='uv',
            field=models.PositiveIntegerField(default=0, verbose_name='点击量'),
        ),
    ]
