# Generated by Django 3.1.8 on 2021-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210518_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraise',
            name='star',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='评星'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='uv',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待付款'), (1, '待配送'), (2, '配送中'), (3, '已取消'), (4, '拒收退款'), (5, '已确认收货')], default=0, verbose_name='状态'),
        ),
    ]
