# Generated by Django 3.1.8 on 2021-05-30 07:38

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210525_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-uv', '-created_time'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='是否可被推荐'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='正文'),
        ),
    ]
