# Generated by Django 3.1.4 on 2021-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('welcome', models.TextField(default='八鱼樱桃沟欢迎您！', verbose_name='关注后欢迎语')),
                ('default_reply', models.TextField(default='', verbose_name='默认自动回复')),
            ],
            options={
                'verbose_name': '自动回复',
                'verbose_name_plural': '自动回复',
                'get_latest_by': 'created_time',
            },
        ),
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.TextField(default='', verbose_name='自定义菜单配置')),
            ],
            options={
                'verbose_name': '自定义菜单',
                'verbose_name_plural': '自定义菜单',
                'get_latest_by': 'created_time',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.PositiveIntegerField(verbose_name='实付款')),
                ('out_trade_no', models.SlugField(blank=True, default='', max_length=64, verbose_name='微信订单号')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, '待付款'), (2, '已付款'), (3, '已退款')], default=1, verbose_name='订单状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '零售订单',
                'verbose_name_plural': '零售订单',
                'ordering': ['-created_time', '-total_fee'],
            },
        ),
    ]
