# Generated by Django 3.2.7 on 2021-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('content', models.CharField(max_length=256, verbose_name='回复内容')),
                ('content_type', models.SmallIntegerField(choices=[(1, '文本'), (2, '图片'), (3, '音频'), (4, '视频')], default=1, verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '消息内容',
                'verbose_name_plural': '消息内容',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.PositiveIntegerField(verbose_name='实付款')),
                ('out_trade_no', models.SlugField(blank=True, default='', max_length=64, verbose_name='微信订单号')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, '待付款'), (2, '已付款'), (3, '已退款')], default=1, verbose_name='订单状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '零售订单',
                'verbose_name_plural': '零售订单',
                'ordering': ['-created_time', '-total_fee'],
            },
        ),
        migrations.CreateModel(
            name='WxAutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=20, unique=True, verbose_name='规则名称')),
                ('keyword', models.CharField(max_length=20, unique=True, verbose_name='关键词')),
                ('reply_type', models.SmallIntegerField(choices=[(0, '随机回复一条'), (1, '全部回复')], default=1, verbose_name='回复方式')),
                ('contents', models.ManyToManyField(to='wechat.Content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '自动回复',
                'verbose_name_plural': '自动回复',
            },
        ),
    ]
