# Generated by Django 3.1.8 on 2021-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('content', models.CharField(max_length=256, verbose_name='回复内容')),
                ('content_type', models.SmallIntegerField(choices=[(1, '文本'), (2, '图片'), (3, '音频'), (4, '视频')], default=1, verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '消息内容',
                'verbose_name_plural': '消息内容',
            },
        ),
        migrations.CreateModel(
            name='WxAutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=20, unique=True, verbose_name='规则名称')),
                ('keyword', models.CharField(max_length=20, unique=True, verbose_name='关键词')),
                ('reply_type', models.SmallIntegerField(choices=[(0, '随机回复一条'), (1, '全部回复')], default=1, verbose_name='回复方式')),
                ('contents', models.ManyToManyField(to='wechat.Content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '自动回复',
                'verbose_name_plural': '自动回复',
            },
        ),
        migrations.DeleteModel(
            name='AutoReply',
        ),
        migrations.DeleteModel(
            name='CustomMenu',
        ),
    ]
